version: '3.9'

services:
  django_backend:
    build: ./backend
    image: 'django_backend:latest'
    container_name: django_backend
    volumes:
      - ./backend/:/usr/src/backend/
    ports:
      - 80:8000
    env_file:
      - ./.env
    depends_on:
      - postgresql

  postgresql:
    image: postgres:latest
    container_name: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: example
